---
# Author: CP

- name: Check if replicated profile already exists
  command: "ceph --cluster {{ cluster }} osd erasure-code-profile get {{ item.name }}"
  changed_when: false
  failed_when: false
  register: check_existing_ec

- debug:
    msg: "Skipping profile {{ item.name }} because already exist and force not set"
  when:
    - check_existing_ec.rc == 0
    - not item.force | default(false)  

- debug:
    msg: "Updating profile {{ item.name }} as force is set"
  when:
    - check_existing_ec.rc == 0
    - item.force | default(false)  

- name: "Updating replicated profile {{ item.name }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd crush rule create-replicated {{ item.name }} {{ item.root }} {{ item.crush_failure_domain }} --force"
  changed_when: false
  when:
    - check_existing_ec.rc == 0
    - item.force | default(false)  

- name: "Create new replicated profile {{ item.name }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd crush rule create-replicated {{ item.name }} {{ item.root }} {{ item.crush_failure_domain }}"
  changed_when: false
  when:
    - check_existing_ec.rc != 0

