---
- name: "Check if pool {{ item.name }} already exists"
  command: "ceph --cluster {{ cluster }} osd pool get {{ item.name }} pg_num"
  changed_when: false
  failed_when: false
  register: check_existing_cephpool_ec

- name: "Create pool {{ item.name }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool create {{ item.name }} {{ item.pgs | default(osd_pool_default_pg_num) }} {{ item.pgs | default(osd_pool_default_pg_num) }} erasure {{ item.ec_profile }}"
  changed_when: false
  when:
  - check_existing_cephpool_ec.rc != 0

- name: "Customize pool pgnum {{ item.name }}: {{ item.pgs | default(osd_pool_default_pg_num) }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool set {{ item.name }} pg_num {{ item.pgs | default(osd_pool_default_pg_num) }}"
  changed_when: false
  when:
  - check_existing_cephpool_ec.rc == 0

- name: "Set pool {{ item.name }} target_ratio: {{ item.target_size_ratio | default(0) }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool set {{ item.name }} target_size_ratio {{ item.target_size_ratio }}"
  changed_when: false
  when:
  - item.target_size_ratio is defined

- name: "Set pool {{ item.name }} application: {{ app }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool application enable {{ item.name }} {{ app }}"
  changed_when: false
  loop: "{{ item.applications }}"
  loop_control:
    loop_var: app
  when:
  - item.applications is defined

- name: "Set pool {{ item.name }} application: {{ app }}"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool set {{ item.name }} allow_ec_overwrites true"
  changed_when: false
  loop: "{{ item.applications }}"
  loop_control:
    loop_var: app
  when:
  - item.applications is defined
  - app == "cephfs"

- name: "Init rbd pools"
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} rdb init pool {{ item.name }}"
  changed_when: false
  loop: "{{ item.applications }}"
  loop_control:
    loop_var: app
  when:
  - item.applications is defined
  - app == "rdb"