---
# Author: CP

- name: Create replicated profiles
  hosts: "{{ groups['mons'][0] }}"
  become: true

  tasks:
    - include_tasks: create_replicated_profile.yml
      loop: "{{ ceph_replicated_profiles }}"

- name: Create replicated pools
  hosts: "{{ groups['mons'][0] }}"
  become: true

  tasks:
    - include_tasks: create_replicated_pool.yml
      loop: "{{ ceph_pools_replicated }}"

- name: Create EC profiles
  hosts: "{{ groups['mons'][0] }}"
  become: true

  tasks:
    - include_tasks: create_ec_profile.yml
      loop: "{{ ceph_ec_profiles }}"

- name: Create EC pools
  hosts: "{{ groups['mons'][0] }}"
  become: true

  tasks:
    - include_tasks: create_ec_pool.yml
      loop: "{{ ceph_pools_ec }}"

