---
# Author: CP

- name: Install smartmontools
  hosts:
    - mons
    - osds
  become: true

  tasks:
    - name: install smartmontools
      yum:
        name: smartmontools
        state: latest
      